export const RECONCILIATION_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  GRE_ESTADO_CONCILIADA: 'CONCILIADA',
  GRE_ESTADO_CON_DIFERENCIA: 'CON_DIFERENCIA',
  CONCILIACION_COMPLETADA: 'COMPLETADA',
  CONCILIACION_CON_DIFERENCIAS: 'CON_DIFERENCIAS',
} as const;
