export const REFRESH_TOKEN_COOKIE = 'gre_refresh_token';

export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES: '15m',
  REFRESH_TOKEN_EXPIRES: '7d',
  REFRESH_TOKEN_EXPIRES_MS: 7 * 24 * 60 * 60 * 1000,
  PASSWORD_RESET_EXPIRES_MS: 60 * 60 * 1000,
  LOGIN_MAX_ATTEMPTS: 5,
  LOGIN_BLOCK_MINUTES: 15,
  BCRYPT_ROUNDS: 12,
} as const;
