export enum Rol {
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  CONSULTA = 'CONSULTA',
}

export enum GreEstado {
  PENDIENTE = 'PENDIENTE',
  CONCILIADA = 'CONCILIADA',
  CON_DIFERENCIA = 'CON_DIFERENCIA',
  ANULADA = 'ANULADA',
}

export enum TipoMovimiento {
  ENTRADA = 'ENTRADA',
  SALIDA = 'SALIDA',
  AJUSTE = 'AJUSTE',
}

export enum TipoAlerta {
  STOCK_INSUFICIENTE = 'STOCK_INSUFICIENTE',
  DIFERENCIA_GRE = 'DIFERENCIA_GRE',
  DIFERENCIA_KARDEX = 'DIFERENCIA_KARDEX',
  DIFERENCIA_FISICO = 'DIFERENCIA_FISICO',
  STOCK_MINIMO = 'STOCK_MINIMO',
  GRE_PENDIENTE = 'GRE_PENDIENTE',
  TRIBUTARIA = 'TRIBUTARIA',
}

export enum TipoIncidencia {
  GRE_KARDEX = 'GRE_KARDEX',
  GRE_FISICO = 'GRE_FISICO',
  KARDEX_FISICO = 'KARDEX_FISICO',
}

export enum IncidenciaEstado {
  PENDIENTE = 'PENDIENTE',
  REVISADA = 'REVISADA',
  RESUELTA = 'RESUELTA',
}

export enum TipoArchivoGre {
  XML = 'XML',
  PDF = 'PDF',
}

export enum TipoEventoTrazabilidad {
  GRE_EMITIDA = 'GRE_EMITIDA',
  ARCHIVO_CARGADO = 'ARCHIVO_CARGADO',
  MOVIMIENTO_KARDEX = 'MOVIMIENTO_KARDEX',
  STOCK_FISICO_REGISTRADO = 'STOCK_FISICO_REGISTRADO',
  CONCILIACION_INICIADA = 'CONCILIACION_INICIADA',
  CONCILIACION_COMPLETADA = 'CONCILIACION_COMPLETADA',
  CONCILIACION_CON_DIFERENCIA = 'CONCILIACION_CON_DIFERENCIA',
  INCIDENCIA_CREADA = 'INCIDENCIA_CREADA',
  INCIDENCIA_RESUELTA = 'INCIDENCIA_RESUELTA',
}

export enum TipoCatalogo {
  CATEGORIA = 'CATEGORIA',
  UNIDAD = 'UNIDAD',
  UBICACION = 'UBICACION',
  OTRO = 'OTRO',
}

export enum AccionAuditoria {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
}

export enum TipoParametro {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  JSON = 'JSON',
}

export enum NivelRiesgoTributario {
  BAJO = 'BAJO',
  MODERADO = 'MODERADO',
  ALTO = 'ALTO',
  CRITICO = 'CRITICO',
}
